-- MySQL Script generated by MySQL Workbench
-- 10/28/16 16:38:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fs_api_videos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fs_api_videos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fs_api_videos` DEFAULT CHARACTER SET utf8 ;
USE `fs_api_videos` ;

-- -----------------------------------------------------
-- Table `fs_api_videos`.`media_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fs_api_videos`.`media_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fs_api_videos`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fs_api_videos`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `media_category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_media_media_category_idx` (`media_category_id` ASC),
  CONSTRAINT `fk_media_media_category`
    FOREIGN KEY (`media_category_id`)
    REFERENCES `fs_api_videos`.`media_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fs_api_videos`.`media_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fs_api_videos`.`media_video` (
  `media_id` INT NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` TEXT NOT NULL,
  INDEX `fk_media_video_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_media_video_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `fs_api_videos`.`media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fs_api_videos`.`media_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fs_api_videos`.`media_image` (
  `media_id` INT NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` TEXT NOT NULL,
  INDEX `fk_media_image_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_media_image_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `fs_api_videos`.`media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
